### ISSUE TITLE
No shared lobbies possible

### ISSUE THREAD

**Issue by LeskovarLukas** [AmongHTBLuVA/AmongHTL#13]
When starting a game only one player connects to one lobby.
Don't know if it's just on the kill-player feature or a more severe error.

**Comment by LeskovarLukas** [comment]
Dont know if it helps but when starting a lobby the log message for checkLogOn returns null for the user name

**Comment by LeskovarLukas** [comment]
seems like the client cant reconnect after opening a lobby

**Comment by Kleinrad** [comment]
If you are connecting with the same browser, then that's because you are the same user, and you can't join yourself. There is already an issue to notify the user that he is already logged in, if you want to test you can use other browsers or the private mode of each browser, because that's a different session and gets a unique ID.
I can't find another reason, I tried it out myself, and it worked fine.

Hope that helps
